default: &DEFAULT
  gateway_server: 'login.aws-est.where.com'
  deploy_via: remote_cache
  user: deploy
  default_branch: master
  use_sudo: false
  scm: git
  uses_resque: false
  uses_whenever_cron: false

staging: 
  <<: *DEFAULT
  env_name: web-stg
  rails_env: staging

staging2: 
  <<: *DEFAULT
  env_name: web-stg2
  rails_env: staging

mobile: 
  <<: *DEFAULT
  env_name: web-mobile
  rails_env: staging

production: &PROD
  <<: *DEFAULT
  env_name: web.ss
  rails_env: production
  verify_intent: false
  copy_exclude:
    - .git*

debug:
  <<: *PROD
  env_name: web-dbg
  verify_intent: false
