default: &DEFAULT
  # used by all apps
  gateway_server: 'login.aws-est.where.com'
  deploy_via: export
  copy_cache: true
  copy_exclude:
    - .git*
  user: deploy
  default_branch: master
  scm: git
  use_sudo: false
  servers: [app01, app02]
  db_server: app01
  cron_server: app01

  verify_intent: false
  use_newrelic: true
  use_airbrake: true
  use_resque: false
  use_whenever_cron: false

  # used by > ruby 1.8.7 apps
  use_paypal: false
  use_asset_sync: true
  use_rvm: true
  use_unicorn: true
  rvm_ruby: ruby-1.9.3-p0
  rvm_gemset: global
  seed_on_migration: false

  # used by legacy apps (smb_portal, nearbuys, where_web, lg)
  use_asset_id: false
  use_passenger: false
  use_database: true
  use_hoptoad: false

staging:
  <<: *DEFAULT
  env_name: cm-stg.ts
  rails_env: staging

qa:
  <<: *DEFAULT
  env_name: cm-qa.ts
  rails_env: qa

production:
  <<: *DEFAULT
  env_name: cm.ts
  rails_env: production
  verify_intent: true

