default: &DEFAULT
  gateway_server: 'login.aws-est.where.com'
  deploy_via: export
  copy_cache: true
  copy_exclude:
    - .git*
  user: deploy
  default_branch: master
  scm: git
  use_newrelic: true
  use_hoptoad: true
  use_database: true
  use_sudo: false
  use_resque: false
  use_whenever_cron: false
  use_paypal: false
  use_asset_sync: true
  use_asset_id: false
  servers: [app01, app02]
  db_server: app01
  cron_server: app01
  rvm_ruby: ruby-1.9.3-p0
  rvm_gemset: global
  verify_intent: false

staging:
  <<: *DEFAULT
  env_name: cm-stg.ts
  rails_env: staging

production:
  <<: *DEFAULT
  env_name: cm.ts
  rails_env: production
  verify_intent: true

