default: &DEFAULT
  # used by all apps
  gateway_server: 'login.aws-est.where.com'
  deploy_via: export
  copy_cache: true
  copy_exclude:
    - .git*
  user: deploy
  default_branch: master
  scm: git
  use_sudo: false
  servers: [app01, app02]
  db_server: app01
  cron_server: app01
  daemon_server:

  ruby_version: 1.9.3-p123

  verify_intent: false
  use_newrelic: true
  use_airbrake: true
  use_whenever_cron: false
  config_files: []

  use_asset_sync: true
  use_rbenv: true
  use_unicorn: true
  use_hoptoad: false

  seed_on_migration: false
  use_database: true

  # used by legacy apps (smb_portal, nearbuys, where_web, lg)
  use_asset_id: false
  use_passenger: false

staging:
  <<: *DEFAULT
  env_name: cm-stg.ts
  rails_env: staging

qa:
  <<: *DEFAULT
  env_name: cm-qa.ts
  rails_env: qa

pilot:
  <<: *DEFAULT
  env_name: cm-pilot.ts
  rails_env: pilot

production:
  <<: *DEFAULT
  env_name: cm.ts
  rails_env: production
  verify_intent: true

