default: &DEFAULT
  gateway_server: 'login.aws-est.where.com'
  deploy_via: remote_cache
  user: deploy
  default_branch: master
  use_sudo: false
  scm: git
  uses_resque: false
  uses_whenever_cron: false
  uses_newrelic: true
  uses_hoptoad: true
  uses_database: true
  uses_asset_id: true
  uses_asset_sync: false
  servers: [app01, app02]
  db_server: app01
  cron_server: app01
  rvm_ruby: ruby-1.8.7-p334
  rvm_gemset: global

staging: 
  <<: *DEFAULT
  env_name: web-stg
  rails_env: staging

staging2: 
  <<: *DEFAULT
  env_name: web-stg2
  rails_env: staging2

sandbox:
  <<: *DEFAULT
  env_name: web-rvm
  rails_env: staging
  number_of_app_servers: 1

demo:
  <<: *DEFAULT
  env_name: web-demo
  rails_env: demo

mobile: 
  <<: *DEFAULT
  env_name: web-touch-stg
  rails_env: staging

production: &PROD
  <<: *DEFAULT
  env_name: web.ss
  rails_env: production
  verify_intent: false
  copy_exclude:
    - .git*

debug:
  <<: *PROD
  env_name: web-dbg
  verify_intent: false
