default: &DEFAULT
  gateway_server: 'login.aws-est.where.com'
  deploy_via: export
  copy_cache: true
  copy_exclude:
    - .git*
  user: deploy
  default_branch: master
  scm: git
  use_newrelic: true
  use_hoptoad: true
  use_database: true
  use_sudo: false
  use_resque: false
  use_whenever_cron: false
  use_paypal: false
  use_asset_sync: true
  servers: [app01, app02]
  db_server: app01
  cron_server: app01
  rvm_ruby: jruby-1.6.5
  rvm_gemset: global
  verify_intent: false

staging: 
  <<: *DEFAULT
  env_name: web-stg
  rails_env: staging

staging2: 
  <<: *DEFAULT
  env_name: web-stg2
  rails_env: staging2

rvm:
  <<: *DEFAULT
  env_name: web-rvm-stg
  rails_env: staging

rvm-prod:
  <<: *DEFAULT
  env_name: web-rvm
  rails_env: production
  verify_intent: true

cumbie:
  <<: *DEFAULT
  env_name: rec
  rails_env: production

demo:
  <<: *DEFAULT
  env_name: web-demo
  rails_env: demo

mobile: 
  <<: *DEFAULT
  env_name: web-touch-stg
  rails_env: staging

production: &PROD
  <<: *DEFAULT
  env_name: web.ss
  rails_env: production
  verify_intent: true

debug:
  <<: *PROD
  env_name: web-dbg
